preprocessing:
    root_dicom_folder: ./data/DICOM
    dcm2niix_bin: /usr/local/bin/dcm2niix
    fslreorient2std_bin: //opt/ohpc/pub/modulefiles/fsl/6.0.4
    fslval_bin: //opt/ohpc/pub/modulefiles/fsl/6.0.4


data_preparation:
    image_size_x: 256
    image_size_y: 256
    image_size_z: 25

training:
    train_label_file: ./training/in
    output_folder: ./training/out

testing:
    test_label_file: ./testing/in
    output_folder: ./testing/out
    
post_processing:
    prediction_file: ~./testing/out/Predictions_model_all_brain_tumor_data.csv

network:
    batch_size: 32
    nb_epoch: 100
