preprocessing:
    root_dicom_folder: /DDS/data/DICOM
    dcm2niix_bin: /usr/local/bin/dcm2niix  #not used anymore as dcm2niix is installed as a python package
    fslreorient2std_bin: /opt/ohpc/pub/apps/fsl/6.0.4/bin/fslreorient2std
    fslval_bin: /opt/ohpc/pub/apps/fsl/6.0.4/bin/fslval


data_preparation:
    image_size_x: 256
    image_size_y: 256
    image_size_z: 25

training:
    train_label_file: ../data/DATA/labels.txt
    output_folder: ../training/out

testing:
    test_label_file: ../testing/in
    output_folder: ../testing/out
    
post_processing:
    prediction_file: ../testing/out/Predictions_model_all_brain_tumor_data.csv

network:
    batch_size: 32
    nb_epoch: 100
